### ISSUE TITLE
Use .wav audio directly instead of converting to .mp3

### ISSUE THREAD

**Issue by ElnuDev** [ElnuDev/hebi#12]
Currently, the .wav files in the `dev_assets` folder cause errors when used, even with the `wav` feature of Bevy enabled. See [this thread](https://discord.com/channels/691052431525675048/742884593551802431/882692827111383090) on the [Bevy Discord server](https://discord.gg/bevy) for more info. The files seem to play fine, so I'm not sure if this is some issue with the encoding of the files that [jsfxr](https://sfxr.me) outputs, or if there's a potential bug in Bevy. Either way, it'd be way cleaner use the original .wav files directly instead of having to convert them .mp3 using a shell script like is being done currently and store both in this repository.

**Comment by grtcdr** [comment]
You're going to want to look into [rodio](https://github.com/RustAudio/rodio) which is an abstraction (extension?) over many audio encoders/decoders, namely [hound](https://github.com/ruuda/hound) for the WAV format.

**Comment by ElnuDev** [comment]
There was an issue with jsfxr — one of the community members on the Bevy Discord fixed the issue with [this PR](https://github.com/chr15m/jsfxr/pull/6), and is now live on the site. Hebi is now using the fixed .wav files directly, but keeping the `mp3` feature of Bevy in case the user wants to use .mp3 files.

**Comment by grtcdr** [comment]
Good to hear :)
