### ISSUE TITLE
Building with release flag hangs on MacOS 10.15.6

### ISSUE THREAD

**Issue by aaronzshey** [ElnuDev/hebi#23]
These are the steps I followed:
- Clone the repo
- Install rust nightly
- `rustup show` returns this:
```
~/hebi main
▲ rustup show
Default host: x86_64-apple-darwin
rustup home:  /Users/cog/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
nightly-x86_64-apple-darwin

active toolchain
----------------

nightly-x86_64-apple-darwin (directory override for '/Users/cog/hebi')
rustc 1.57.0-nightly (c3c0f80d6 2021-09-14)
```

- run `cargo build --release --verbose` 
- Cook an egg with my laptop fans 
- Watch as `hebi` hangs on 299/300.  I tried waiting up to 7 minutes and it didn't get unstuck.  This is the output, if anyone can understand it:
![Screen Shot 2021-09-16 at 11 16 26 AM](https://user-images.githubusercontent.com/44917034/133664474-c9bdbe01-8784-4c1a-82d0-cca5d0a5ed1c.png)

Other notes: The build size is about 500MB.  A lot better than 1.26GB, but far bigger than linux or windows builds.

**Comment by kroltan** [comment]
Can you try building [without stripping][1]? (Not that kind! Naughty mind)

[1]: https://github.com/ElnuDev/hebi#building-from-source

**Comment by aaronzshey** [comment]
Thanks!  I'll try building without any experimental features with rust stable.

**Comment by aaronzshey** [comment]
I just did that, with removing the stripping lines and then using `rustup default stable` but it still hung at the final step.
<img width="860" alt="Screen Shot 2021-09-17 at 10 16 54 AM" src="https://user-images.githubusercontent.com/44917034/133828347-7e16d483-3e18-4e4e-b868-f53d98fa0d9e.png">
