### ISSUE TITLE
Spawn functions clunkiness

### ISSUE THREAD

**Issue by kroltan** [ElnuDev/hebi#4]
You might have that feeling too:

Currently, if any piece of code wants to spawn a snake, segment, or wall, the system needs to query for those resources and pass them along up to and including the call site. There are like 8 parameters each so it is very verbose, and if you ever need to add something else to the spawn logic (e.g. suppose you later want to add sprites), updating the call sites will be a chore.

This can be substantially improved by either:

 - **Implementing your own [`Command`](https://docs.rs/bevy/0.5.0/bevy/ecs/system/trait.Command.html)**, fetching the dependencies from the world inside the `write` function. This would make the call site look sorta like this:
   ```rs
   commands.add(SnakeSpawnCommand);
   ```
   Or even in this specific case, move the spawn-location-picking logic to the actual respawn system, and have the command take parameters:
   ```rs
   commands.add(SnakeSpawnCommand { x: 4, y: 6, direction: Direction::Up });
   ```
 - **Using an [`Event`](https://github.com/bevyengine/bevy/blob/main/examples/ecs/event.rs), and a late-running system** that listens to it to do the actual spawning. Register an [`Event` type](https://docs.rs/bevy/0.5.0/bevy/app/struct.AppBuilder.html#method.add_event), and make a system that runs as late as possible in the frame that reads the events and the required dependencies, spawning the entities. The call site would then look like:
   ```rs
   snake_spawn_event_writer.send(SnakeSpawnEvent { x: 4, y: 6, direction: Direction::Up });
   ```

**Comment by ElnuDev** [comment]
I was planning on setting up an `Event` for this soon! Having all those parameters is super fiddly. I didn't know about the alternate `Command` approach, though. I guess here `Event` would be preferable, so that way the event could be written at any time during the frame and then always processed at the end of the frame when the event reader system runs. I'll get to this soon, thanks!

**Comment by kroltan** [comment]
Both do that, since `Command`s are also flushed at the end of the frame.

But indeed `Event`s are in theory better, simply because you will have a reader system, which means you'll only need to fetch the dependencies once per frame, while if you had multiple of the same command, each command write would require fetching the dependencies again. It's also generally more idiomatic to rely on the "declarative" systems instead of calling getters on `World`.
